INSERT INTO States VALUES (null,'Draft');
INSERT INTO States VALUES (null,'Proposal');
INSERT INTO States VALUES (null,'Rejected');
INSERT INTO States VALUES (null,'New');
INSERT INTO States VALUES (null,'Open');
INSERT INTO States VALUES (null,'Ready');
INSERT INTO States VALUES (null,'In Progress');
INSERT INTO States VALUES (null,'Finished');
INSERT INTO Categories VALUES (null,'Development');
INSERT INTO Categories VALUES (null,'Project Management');
INSERT INTO Courses VALUES (null,'Project Management 101',5,1,1,1,'','');
INSERT INTO Courses VALUES (null,'NET Technology',4,1,1,1,'','');
INSERT INTO Courses VALUES (null,'Oracle',2,2,1,1,'','');
INSERT INTO Courses VALUES (null,'Java',1,2,1,1,'','');
INSERT INTO Details VALUES (null,'lecturer-a@tc.edu','Bla-bla-bla','Bla-bla-bla',2,2);
INSERT INTO Details VALUES (null,'lecturer-a@tc.edu','Foo-foo-foo','Foo-foo-foo',2,2);
INSERT INTO Details VALUES (null,'lecturer-b@tc.edu','O-o-o','O-o-o',1,1);
INSERT INTO Details VALUES (null,'lecturer-b@tc.edu','Java-java-java','Java-java-java',1,1);
INSERT INTO Roles VALUES (null,'Knowledge Manager');
INSERT INTO Roles VALUES (null,'Department Manager');
INSERT INTO Roles VALUES (null,'Lector');
INSERT INTO Roles VALUES (null,'User');
INSERT INTO Users VALUES (null,'km','km@tc.edu','123',1);
INSERT INTO Users VALUES (null,'dm','dm.tc.edu@gmail.com','123',2);
/* Password for dm.tc.edu@gmail.com: dmtcedudmtcedu                         */
INSERT INTO Users VALUES (null,'lecturer-a','lecturer-a@tc.edu','123',3);
INSERT INTO Users VALUES (null,'lecturer-b','lecturer-b@tc.edu','123',3);
INSERT INTO Users VALUES (null,'user-a','user-a@tc.edu','123',4);
INSERT INTO Users VALUES (null,'user-b','user-b@tc.edu','123',4);
INSERT INTO Users VALUES (null,'user-c','user-c@tc.edu','123',4);
INSERT INTO Subscribes VALUES (2,5);
INSERT INTO Subscribes VALUES (1,6); 
INSERT INTO Attends VALUES (1,5,0);
