<html>
<body>
<p>${ManagerName} had made a decision
<p>----------------------------------------------------
<p>
	<table>
		<tr>
			<td>Name:</td>
			<td>${CourseName}</td>
		</tr>
		<tr>
			<td>Lecturer:</td>
			<td>${CourseLecturer}</td>
		</tr>
	</table>
</p>    
<p>----------------------------------------------------
<p>
	<table>
		<tr>
			<td>Decision:</td>
			<td>${ManagerDecision}</td>
		</tr>
		<tr>
			<td>Reason:</td>
			<td>${ManagerReason}</td>
		</tr>
	</table>
</p>
</body>
</html>