<html>
<body>
<p>Course still needs your vote!
<p>----------------------------------------------------
<p>
	<table>
		<tr>
			<td>Name:</td>
			<td>${CourseName}</td>
		</tr>
		<tr>
			<td>Lecturer:</td>
			<td>${CourseLecturer}</td>
		</tr>
	</table>
</p>    
<p>----------------------------------------------------
<p>
</body>
</html>